# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tucson North Stake YW Camp 2016
description: "Operation: Press Forward"
# baseurl: "/"
url: "https://tnsywcamp.github.io/"

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Blog / news url
permalink: /news/:title/

# Prose
prose:
  siteurl: 'https://tnsywcamp.github.io/'
  media: 'images'
  ignore:
    - /_layouts
    - /_includes
    - /_sass
    - /css
    - /_site
    - Gemfile
    - Gemfile.lock
    - feed.xml
    - /.sass-cache
    - README.md
  metadata:
    /_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "textarea"
          placeholder: "Add your post title here"
